### ISSUE TITLE
Pantalla de Login

### ISSUE THREAD

**Issue by gadd-gj** [gadd-gj/proyectoParcial#1]
**La pantalla de inicio de sesión deberá cumplir con la siguiente estructura:**

> 1. Fondo de la página

- [ ] Color: Hexadecimal: #071B2A // RGB: (7, 27, 42)

> 2. Contenedor de login

- [ ] Color: Hexadecimal #343434 RGB: 52 52 52

> 3. Cabecera de login
- [ ] Icono/logo y nombre de la página

> 4. Cuerpo de login

- [ ] Botones:  Hexadecimal #1B7D8C RGB: 27 125 140
- [ ] Input para ingresar usuario
- [ ] Input para ingresar contraseña

> 5. Pie de login

- [ ] Nombre de la empresa
