### ISSUE TITLE
Landing page 

### ISSUE THREAD

**Issue by gadd-gj** [gadd-gj/proyectoParcial#2]
**La pantalla del _landin page_ deberá cumplir con la siguiente estructura:**

> 1. Fondo de la página

- [ ] Color: Hexadecimal #D3D3D3 || RGB: (211, 211, 211)

> 2. Barra de navegación

- [ ] Color de fondo: Hexadecimal: #343434 || RGB: (52, 52, 52)
- [ ] Color de texto: Hexadecimal: #000000

> 3.  Botones

- [ ] Color: Hexadecimal: #1B7D8C || RGB: (27, 125, 140)

> 4. Portada
- [ ] En la parte superior de la pagina se deberá colocar esta imagen como portada
![imagenLand](https://user-images.githubusercontent.com/56319579/94983746-64de4700-050b-11eb-8c80-fba0f286166b.jpeg)
