### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by gadd-gj** [gadd-gj/proyectoParcial#3]
**La pantalla del _landin page_ deberá cumplir con la siguiente estructura:**

> 1. Fondo de la página

- [ ] Color: Hexadecimal #D3D3D3 || RGB: (211, 211, 211)

> 2. Barra de navegación

- [ ] Color de fondo: Hexadecimal: #343434 || RGB: (52, 52, 52)
- [ ] Color de texto: Hexadecimal: #000000

> 3.  Botones

- [ ] Color: Hexadecimal: #1B7D8C || RGB: (27, 125, 140)

> 4. Mapa

- [ ] Se colocará un mapa del país de México para fines estadísticos
